### ISSUE TITLE
(Fix) Search is not working

### ISSUE THREAD

**Issue by igorbarinov** [oraclesorg/chain-explorer#1]
- on Sokol
`Unexpected token s`

![image](https://user-images.githubusercontent.com/424628/34322436-6cdfef5c-e7f5-11e7-9b15-34d2e91a564d.png)

**Comment by phahulin** [comment]
This exception was caused by nginx rewriting Content-Type header. Fixed in 
https://github.com/poanetwork/deployment-playbooks/commit/675e546e276d6a4b73e82949561aaf6315cad266
