### ISSUE TITLE
(Fix) Repo URL in README

### ISSUE THREAD

**Issue by varasev** [oraclesorg/chain-explorer#3]
There is an old repo URL in README:

> Clone this repository to your local machine: git clone https://github.com/gobitfly/etherchain-light --recursive (Make sure to include --recursive in order to fetch the solc-bin git submodule)

**Comment by phahulin** [comment]
Fixed in https://github.com/poanetwork/chain-explorer/commit/010f8517c07a917a7ed9e5ebde01d763e86b4060
